export interface Location {
  code: string;
  name: string;
}

export const locations: Location[] = [
  { code: 'GN00', name: 'General' },
  { code: 'IN00', name: 'Infrastructure' },
  { code: 'MB00', name: 'Mobilisation' },
  { code: 'ES01', name: 'ESB-01-AP Storage Building' },
  { code: 'ES02', name: 'ESB-02-AP Storage Handling Building' },
  { code: 'ES03', name: 'ESB-03-Fuse Storage' },
  { code: 'ES04', name: 'ESB-04-Warhead Storage Building' },
  { code: 'ES05', name: 'ESB-05-Ammunition Storage Building-1' },
  { code: 'ES06', name: 'ESB-06-Ammunition Storage Building-2' },
  { code: 'ES07', name: 'ESB-07-Ammunition Storage Building-3' },
  { code: 'ES08', name: 'ESB-08-Ammunition Storage Building-4' },
  { code: 'ES09', name: 'ESB-09-Storage for Destruction' },
  { code: 'EW01', name: 'EWB-01-Hammer Mill Building' },
  { code: 'EW02', name: 'EWB-02-AP Storage and Conditioning Building' },
  { code: 'EW03', name: 'EWB-03-Mixer Building' },
  { code: 'EW04', name: 'EWB-04-Premix and Mixbowl Cleaning Building' },
  { code: 'EW05', name: 'EWB-05-Propellant Casting Building' },
  { code: 'EW06', name: 'EWB-06-Propellant Mandrel Disassembly Building' },
  { code: 'EW07', name: 'EWB-07-X-ray and Quality Control Building' },
  { code: 'EW08', name: 'EWB-08-Laboratory Building' },
  { code: 'EW09', name: 'EWB-09-Small Scale Propellant Assembly Firing Test' },
  { code: 'EW10', name: 'EWB-10-Conditioning Building <Small Scale Propellant Assembly>' },
  { code: 'EW11', name: 'EWB-11-Warhead Filling and Assembly Building' },
  { code: 'EW12', name: 'EWB-12-Warhead Press Building' },
  { code: 'EW13', name: 'EWB-13-Final Assembly Building' },
  { code: 'GF01', name: 'GFB-01-Main Entrance Check Point' },
  { code: 'GF02', name: 'GFB-02-Main Entrance Building <pedestrian>' },
  { code: 'GF03', name: 'GFB-03-Management_Administrative_R&D Office' },
  { code: 'GF04', name: 'GFB-04-Cafeteria <Dining Hall Building>' },
  { code: 'GF05', name: 'GFB-05-Health Center' },
  { code: 'GF06', name: 'GFB-06-Data Center' },
  { code: 'GF07', name: 'GFB-07-Facility Maintanance Office and Workshop' },
  { code: 'GF08', name: 'GFB-08-Fire Station' },
  { code: 'GF09', name: 'GFB-09-Heating Plant' },
  { code: 'GF10', name: 'GFB-10-Energetic Area Entrance Building' },
  { code: 'GF11', name: 'GFB-11-Security Tower <8 units>' },
  { code: 'GF12', name: 'GFB-12-Main Transformer Building' },
  { code: 'G13A', name: 'GFB-13A-Transformer Building-A' },
  { code: 'G13B', name: 'GFB-13B-Transformer Building-B' },
  { code: 'G13C', name: 'GFB-13C-Transformer Building-C' },
  { code: 'G13D', name: 'GFB-13D-Transformer Building-D' },
  { code: 'G13E', name: 'GFB-13E-Transformer Building-E' },
  { code: 'G13F', name: 'GFB-13F-Transformer Building-F' },
  { code: 'G13G', name: 'GFB-13G-Transformer Building-G' },
  { code: 'G13H', name: 'GFB-13H-Transformer Building-H' },
  { code: 'G13I', name: 'GFB-13I-Transformer Building-I' },
  { code: 'GF14', name: 'GFB-14-Water Tank Building <Potable water>' },
  { code: 'GF15', name: 'GFB-15-Fire Water Tank Building' },
  { code: 'GF16', name: 'GFB-16-Waste Water Purification Plant' },
  { code: 'GF17', name: 'GFB-17-Industrial Waste Water Purification Plant' },
  { code: 'GF18', name: 'GFB-18-Temporary Waste Holding Area' },
  { code: 'GF19', name: 'GFB-19-Main Entrance Logistics' },
  { code: 'IS01', name: 'ISB-01-Mixbowl_Mandrel and Tool Storage' },
  { code: 'IS02', name: 'ISB-02-Inert Material Storage Building <Incoming Inspection and Calibration>' },
  { code: 'IS03', name: 'ISB-03-Chemical Material Storage Building' },
  { code: 'IW01', name: 'IWB-01-Motor Case Production Building' },
  { code: 'IW1A', name: 'IWB-01A-Motor Case Preform Production Building' },
  { code: 'IW02', name: 'IWB-02-Motor Case Insulation and Composite' },
  { code: 'IW03', name: 'IWB-03-Spray Application Building' },
  { code: 'IW04', name: 'IWB-04-Control Building' },
  { code: 'IW05', name: 'IWB-05-Small Scale Propellant Assembly Test Control' },
  { code: 'IW06', name: 'IWB-06-Propellant Employee Office Building' },
  { code: 'IW07', name: 'IWB-07-Warhead Employee Office Building' }
]; 